### PR TITLE
Create MOST-REPORTED-ERROR.developers & MOST-REQUESTED-FEATURES.developers

### PR DESCRIPTION
**Pull request by EnergyCube**
Files containing the most common limbo errors reported by the PlayStore on the unofficial Limbo app and the most requested features.

### CODE REVIEW

**Comment by ZReC** [comment]
**Hello guys! I report this crash, it happens to me when I try to open an .iso or browsing a file.**

```
--------- beginning of main
V/vm-executor-jni.cpp(19123): Processing params
V/vm-executor-jni.cpp(19123): Starting VM...
V/vm-executor-jni.cpp(19123): Loading lib: /data/data/com.limbo.emu.main/lib/libqemu-system-x86_64.so
V/vm-executor-jni.cpp(19123): Loading symbol main...
W/limbo_compat_filesystem.c(19123): Could not fopen: /data/data/com.limbo.emu.main/cache/limbo//usr/local/etc/qemu/qemu.conf, r, 0x0
I/VncCanvas(19123): Connecting to localhost, port 5901...
V/VncCanvas(19123): Connected to server
I/VncCanvas(19123): RFB server supports protocol version 3.8
I/VncCanvas(19123): Using RFB protocol version 3.8
D/debug   (19123): bitPref=1
I/VncCanvas(19123): No authentication needed
I/System.out(19123): No authentication: success
I/VncCanvas(19123): Desktop name is QEMU
I/VncCanvas(19123): Desktop size is 720 x 400
I/FBBM    (19123): bitmapsize = (720,400)
W/InputEventReceiver(19123): Attempted to finish an input event but the input event receiver has already been disposed.
D/AndroidRuntime(19123): Shutting down VM
--------- beginning of crash
E/AndroidRuntime(19123): FATAL EXCEPTION: main
E/AndroidRuntime(19123): Process: com.limbo.emu.main, PID: 19123
E/AndroidRuntime(19123): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT typ=*/* flg=0x43 (has extras) }
E/AndroidRuntime(19123):  at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1872)
E/AndroidRuntime(19123):  at android.app.Instrumentation.execStartActivity(Instrumentation.java:1568)
E/AndroidRuntime(19123):  at android.app.Activity.startActivityForResult(Activity.java:3755)
E/AndroidRuntime(19123):  at android.app.Activity.startActivityForResult(Activity.java:3716)
E/AndroidRuntime(19123):  at com.max2idea.android.limbo.utils.FileManager.promptSDCardAccess(FileManager.java:255)
E/AndroidRuntime(19123):  at com.max2idea.android.limbo.utils.DrivesDialogBox.browse(DrivesDialogBox.java:564)
E/AndroidRuntime(19123):  at com.max2idea.android.limbo.utils.DrivesDialogBox$2.onItemSelected(DrivesDialogBox.java:95)
E/AndroidRuntime(19123):  at android.widget.AdapterView.fireOnSelected(AdapterView.java:914)
E/AndroidRuntime(19123):  at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:903)
E/AndroidRuntime(19123):  at android.widget.AdapterView.access$300(AdapterView.java:48)
E/AndroidRuntime(19123):  at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:873)
E/AndroidRuntime(19123):  at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(19123):  at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(19123):  at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(19123):  at android.app.ActivityThread.main(ActivityThread.java:5343)
E/AndroidRuntime(19123):  at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19123):  at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(19123):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
E/AndroidRuntime(19123):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
```

**"android.intent.action.OPEN_DOCUMENT"** is the problem...

_I use a moto E2, lollipop, last limbo build._

**Comment by EnergyCube** [comment]
> **Hello guys! I report this crash, it happens to me when I try to open an .iso or browsing a file.**
> 
> ```
> --------- beginning of main
> V/vm-executor-jni.cpp(19123): Processing params
> V/vm-executor-jni.cpp(19123): Starting VM...
> V/vm-executor-jni.cpp(19123): Loading lib: /data/data/com.limbo.emu.main/lib/libqemu-system-x86_64.so
> V/vm-executor-jni.cpp(19123): Loading symbol main...
> W/limbo_compat_filesystem.c(19123): Could not fopen: /data/data/com.limbo.emu.main/cache/limbo//usr/local/etc/qemu/qemu.conf, r, 0x0
> I/VncCanvas(19123): Connecting to localhost, port 5901...
> V/VncCanvas(19123): Connected to server
> I/VncCanvas(19123): RFB server supports protocol version 3.8
> I/VncCanvas(19123): Using RFB protocol version 3.8
> D/debug   (19123): bitPref=1
> I/VncCanvas(19123): No authentication needed
> I/System.out(19123): No authentication: success
> I/VncCanvas(19123): Desktop name is QEMU
> I/VncCanvas(19123): Desktop size is 720 x 400
> I/FBBM    (19123): bitmapsize = (720,400)
> W/InputEventReceiver(19123): Attempted to finish an input event but the input event receiver has already been disposed.
> D/AndroidRuntime(19123): Shutting down VM
> --------- beginning of crash
> E/AndroidRuntime(19123): FATAL EXCEPTION: main
> E/AndroidRuntime(19123): Process: com.limbo.emu.main, PID: 19123
> E/AndroidRuntime(19123): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT typ=*/* flg=0x43 (has extras) }
> E/AndroidRuntime(19123):  at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1872)
> E/AndroidRuntime(19123):  at android.app.Instrumentation.execStartActivity(Instrumentation.java:1568)
> E/AndroidRuntime(19123):  at android.app.Activity.startActivityForResult(Activity.java:3755)
> E/AndroidRuntime(19123):  at android.app.Activity.startActivityForResult(Activity.java:3716)
> E/AndroidRuntime(19123):  at com.max2idea.android.limbo.utils.FileManager.promptSDCardAccess(FileManager.java:255)
> E/AndroidRuntime(19123):  at com.max2idea.android.limbo.utils.DrivesDialogBox.browse(DrivesDialogBox.java:564)
> E/AndroidRuntime(19123):  at com.max2idea.android.limbo.utils.DrivesDialogBox$2.onItemSelected(DrivesDialogBox.java:95)
> E/AndroidRuntime(19123):  at android.widget.AdapterView.fireOnSelected(AdapterView.java:914)
> E/AndroidRuntime(19123):  at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:903)
> E/AndroidRuntime(19123):  at android.widget.AdapterView.access$300(AdapterView.java:48)
> E/AndroidRuntime(19123):  at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:873)
> E/AndroidRuntime(19123):  at android.os.Handler.handleCallback(Handler.java:739)
> E/AndroidRuntime(19123):  at android.os.Handler.dispatchMessage(Handler.java:95)
> E/AndroidRuntime(19123):  at android.os.Looper.loop(Looper.java:135)
> E/AndroidRuntime(19123):  at android.app.ActivityThread.main(ActivityThread.java:5343)
> E/AndroidRuntime(19123):  at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime(19123):  at java.lang.reflect.Method.invoke(Method.java:372)
> E/AndroidRuntime(19123):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
> E/AndroidRuntime(19123):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
> ```
> **"android.intent.action.OPEN_DOCUMENT"** is the problem...
> 
> _I use a moto E2, lollipop, last limbo build._

Added :)
Occurrence: unknown
On : Motorola Moto E (Android 5.0, 5.1 (Lollipop) - only XT1527, 6.0 (Marshmallow))
Version : 3.0.1
Comment : Comment: The problem seems to be android.intent.action.OPEN_DOCUMENT or there is no unsuported system file manager (ActivityNotFoundException)

**Comment by EnergyCube** [comment]
Added :)
Occurrence: unknown
On : Motorola Moto E (Android 5.0, 5.1 (Lollipop) - only XT1527, 6.0 (Marshmallow))
Version : 3.0.1
Comment : Comment: The problem seems to be android.intent.action.OPEN_DOCUMENT or there is no unsuported system file manager (ActivityNotFoundException)

**Comment by CodeExecution** [comment]
Seems like Issues aren't enabled in this GitHub repository. Could these please be enabled?

**Comment by EnergyCube** [comment]
@CodeExecution Yeah :relaxed:

**Comment by limboemu** [comment]
Most of these issues are fixed in the latest 4.0.0 version. Also, issues have been re-enabled. Keep in mind releases are not scheduled, in fact there might not be any at all in the future. Support as you might have figured out already doesn't work on a daily basis.

You're welcome to fork, fix, improve, redistribute binaries and code, and most importantly contribute and share in accordance with the [license](https://github.com/limboemu/limbo/blob/master/COPYING).

**Comment by XuQiufeng** [comment]
10-21 16:44:01.644 14102 14102 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-21 16:44:01.644 14102 14102 F DEBUG   : Build fingerprint: 'Redmi/cezanne/cezanne:10/QP1A.190711.020/V12.0.13.0.QJNCNXM:user/release-keys'
10-21 16:44:01.644 14102 14102 F DEBUG   : Revision: '0'
10-21 16:44:01.644 14102 14102 F DEBUG   : ABI: 'arm64'
10-21 16:44:01.644 14102 14102 F DEBUG   : Timestamp: 2020-10-21 16:44:01+0800
10-21 16:44:01.644 14102 14102 F DEBUG   : pid: 13656, tid: 14090, name: VMExecutor  >>> com.limbo.emu.main <<<
10-21 16:44:01.644 14102 14102 F DEBUG   : uid: 10308
10-21 16:44:01.644 14102 14102 F DEBUG   : signal 35 (<debuggerd signal>), code -1 (SI_QUEUE), fault addr --------
10-21 16:44:01.644 14102 14102 F DEBUG   : Abort message: 'attempted to close file descriptor 109, expected to be unowned, actually owned by ParcelFileDescriptor 0xba55910'
10-21 16:44:01.644 14102 14102 F DEBUG   :     x0  0000000000000000  x1  000000000000370a  x2  0000000000000023  x3  000000759b3e7ff0
10-21 16:44:01.644 14102 14102 F DEBUG   :     x4  0000000035356162  x5  0000000035356162  x6  0000000035356162  x7  0000000030313935
10-21 16:44:01.644 14102 14102 F DEBUG   :     x8  00000000000000f0  x9  0000000000000001  x10 0000000000000000  x11 0000007689668cfd
10-21 16:44:01.644 14102 14102 F DEBUG   :     x12 0000007689668ca3  x13 000000759b3e7bb7  x14 0000000000000000  x15 0000000000000057
10-21 16:44:01.644 14102 14102 F DEBUG   :     x16 000000768973d8c8  x17 000000768971ace0  x18 0000000000000001  x19 0000000000003558
10-21 16:44:01.644 14102 14102 F DEBUG   :     x20 000000000000370a  x21 000000759b3e7de0  x22 000000759b3ea018  x23 0000000000000001
10-21 16:44:01.644 14102 14102 F DEBUG   :     x24 000000759b3e7d60  x25 000000759b3e7d20  x26 000000759b3e80e0  x27 0000007589d9e400
10-21 16:44:01.644 14102 14102 F DEBUG   :     x28 00000075fba925c0  x29 000000759b3e80d0
10-21 16:44:01.644 14102 14102 F DEBUG   :     sp  000000759b3e7ca0  lr  00000076896d2bd0  pc  00000076896d2bf4
10-21 16:44:01.800 14102 14102 F DEBUG   : 
10-21 16:44:01.800 14102 14102 F DEBUG   : backtrace:
10-21 16:44:01.800 14102 14102 F DEBUG   :       #00 pc 0000000000086bf4  /apex/com.android.runtime/lib64/bionic/libc.so (fdsan_error(char const*, ...)+380) (BuildId: f5ba4e7e3cee771446d26d581339d879)
10-21 16:44:01.800 14102 14102 F DEBUG   :       #01 pc 00000000000869b0  /apex/com.android.runtime/lib64/bionic/libc.so (android_fdsan_close_with_tag+732) (BuildId: f5ba4e7e3cee771446d26d581339d879)
10-21 16:44:01.800 14102 14102 F DEBUG   :       #02 pc 0000000000087174  /apex/com.android.runtime/lib64/bionic/libc.so (close+16) (BuildId: f5ba4e7e3cee771446d26d581339d879)
10-21 16:44:01.800 14102 14102 F DEBUG   :       #03 pc 00000000002e38f4  /data/app/com.limbo.emu.main-xoGr7ZDZFnq8mXaagNshXQ==/lib/arm64/libqemu-system-x86_64.so
10-21 16:44:01.800 14102 14102 F DEBUG   :       #04 pc 00000000002d1db8  /data/app/com.limbo.emu.main-xoGr7ZDZFnq8mXaagNshXQ==/lib/arm64/libqemu-system-x86_64.so (bdrv_find_protocol+88)
10-21 16:44:01.800 14102 14102 F DEBUG   :       #05 pc 00000000002d6754  /data/app/com.limbo.emu.main-xoGr7ZDZFnq8mXaagNshXQ==/lib/arm64/libqemu-system-x86_64.so
10-21 16:44:01.800 14102 14102 F DEBUG   :       #06 pc 00000000002d7ae4  /data/app/com.limbo.emu.main-xoGr7ZDZFnq8mXaagNshXQ==/lib/arm64/libqemu-system-x86_64.so
10-21 16:44:01.800 14102 14102 F DEBUG   :       #07 pc 00000000002d6b60  /data/app/com.limbo.emu.main-xoGr7ZDZFnq8mXaagNshXQ==/lib/arm64/libqemu-system-x86_64.so
10-21 16:44:01.800 14102 14102 F DEBUG   :       #08 pc 00000000002dee20  /data/app/com.limbo.emu.main-xoGr7ZDZFnq8mXaagNshXQ==/lib/arm64/libqemu-system-x86_64.so (blk_new_open+104)
10-21 16:44:01.800 14102 14102 F DEBUG   :       #09 pc 00000000002ba114  /data/app/com.limbo.emu.main-xoGr7ZDZFnq8mXaagNshXQ==/lib/arm64/libqemu-system-x86_64.so
10-21 16:44:01.800 14102 14102 F DEBUG   :       #10 pc 0000000000327674  /data/app/com.limbo.emu.main-xoGr7ZDZFnq8mXaagNshXQ==/lib/arm64/libqemu-system-x86_64.so (drive_new+2308)
10-21 16:44:01.800 14102 14102 F DEBUG   :       #11 pc 00000000004d9cf0  /data/app/com.limbo.emu.main-xoGr7ZDZFnq8mXaagNshXQ==/lib/arm64/libqemu-system-x86_64.so
10-21 16:44:01.800 14102 14102 F DEBUG   :       #12 pc 0000000000625c40  /data/app/com.limbo.emu.main-xoGr7ZDZFnq8mXaagNshXQ==/lib/arm64/libqemu-system-x86_64.so (qemu_opts_foreach+116)
10-21 16:44:01.800 14102 14102 F DEBUG   :       #13 pc 00000000002bec14  /data/app/com.limbo.emu.main-xoGr7ZDZFnq8mXaagNshXQ==/lib/arm64/libqemu-system-x86_64.so (main+4112)
10-21 16:44:01.800 14102 14102 F DEBUG   :       #14 pc 00000000000013cc  /data/app/com.limbo.emu.main-xoGr7ZDZFnq8mXaagNshXQ==/lib/arm64/liblimbo.so (Java_com_max2idea_android_limbo_jni_VMExecutor_start+744) (BuildId: 7822f9c542a97b60c4f018372e0cfcdba0b5e3e8)
10-21 16:44:01.800 14102 14102 F DEBUG   :       #15 pc 000000000002852c  /data/app/com.limbo.emu.main-xoGr7ZDZFnq8mXaagNshXQ==/oat/arm64/base.odex (art_jni_trampoline+284)
10-21 16:44:01.800 14102 14102 F DEBUG   :       #16 pc 0000000000136334  /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 95b8a178dc0adad199ad5025808e3e5e)
10-21 16:44:01.800 14102 14102 F DEBUG   :       #17 pc 0000000000145060  /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+244) (BuildId: 95b8a178dc0adad199ad5025808e3e5e)
10-21 16:44:01.800 14102 14102 F DEBUG   :       #18 pc 00000000002ddb64  /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+384) (BuildId: 95b8a178dc0adad199ad5025808e3e5e)
10-21 16:44:01.800 14102 14102 F DEBUG   :       #19 pc 00000000002d9938  /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<true, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+656) (BuildId: 95b8a178dc0adad199ad5025808e3e5e)

**Comment by XuQiufeng** [comment]
> 10-21 16:44:01.644 14102 14102 F DEBUG : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
> 10-21 16:44:01.644 14102 14102 F DEBUG : Build fingerprint: 'Redmi/cezanne/cezanne:10/QP1A.190711.020/V12.0.13.0.QJNCNXM:user/release-keys'
> 10-21 16:44:01.644 14102 14102 F DEBUG : Revision: '0'
> 10-21 16:44:01.644 14102 14102 F DEBUG : ABI: 'arm64'
> 10-21 16:44:01.644 14102 14102 F DEBUG : Timestamp: 2020-10-21 16:44:01+0800
> 10-21 16:44:01.644 14102 14102 F DEBUG : pid: 13656, tid: 14090, name: VMExecutor >>> com.limbo.emu.main <<<
> 10-21 16:44:01.644 14102 14102 F DEBUG : uid: 10308
> 10-21 16:44:01.644 14102 14102 F DEBUG : signal 35 (), code -1 (SI_QUEUE), fault addr --------
> 10-21 16:44:01.644 14102 14102 F DEBUG : Abort message: 'attempted to close file descriptor 109, expected to be unowned, actually owned by ParcelFileDescriptor 0xba55910'
> 10-21 16:44:01.644 14102 14102 F DEBUG : x0 0000000000000000 x1 000000000000370a x2 0000000000000023 x3 000000759b3e7ff0
> 10-21 16:44:01.644 14102 14102 F DEBUG : x4 0000000035356162 x5 0000000035356162 x6 0000000035356162 x7 0000000030313935
> 10-21 16:44:01.644 14102 14102 F DEBUG : x8 00000000000000f0 x9 0000000000000001 x10 0000000000000000 x11 0000007689668cfd
> 10-21 16:44:01.644 14102 14102 F DEBUG : x12 0000007689668ca3 x13 000000759b3e7bb7 x14 0000000000000000 x15 0000000000000057
> 10-21 16:44:01.644 14102 14102 F DEBUG : x16 000000768973d8c8 x17 000000768971ace0 x18 0000000000000001 x19 0000000000003558
> 10-21 16:44:01.644 14102 14102 F DEBUG : x20 000000000000370a x21 000000759b3e7de0 x22 000000759b3ea018 x23 0000000000000001
> 10-21 16:44:01.644 14102 14102 F DEBUG : x24 000000759b3e7d60 x25 000000759b3e7d20 x26 000000759b3e80e0 x27 0000007589d9e400
> 10-21 16:44:01.644 14102 14102 F DEBUG : x28 00000075fba925c0 x29 000000759b3e80d0
> 10-21 16:44:01.644 14102 14102 F DEBUG : sp 000000759b3e7ca0 lr 00000076896d2bd0 pc 00000076896d2bf4
> 10-21 16:44:01.800 14102 14102 F DEBUG :
> 10-21 16:44:01.800 14102 14102 F DEBUG : backtrace:
> 10-21 16:44:01.800 14102 14102 F DEBUG : #00 pc 0000000000086bf4 /apex/com.android.runtime/lib64/bionic/libc.so (fdsan_error(char const*, ...)+380) (BuildId: f5ba4e7e3cee771446d26d581339d879)
> 10-21 16:44:01.800 14102 14102 F DEBUG : #01 pc 00000000000869b0 /apex/com.android.runtime/lib64/bionic/libc.so (android_fdsan_close_with_tag+732) (BuildId: f5ba4e7e3cee771446d26d581339d879)
> 10-21 16:44:01.800 14102 14102 F DEBUG : #02 pc 0000000000087174 /apex/com.android.runtime/lib64/bionic/libc.so (close+16) (BuildId: f5ba4e7e3cee771446d26d581339d879)
> 10-21 16:44:01.800 14102 14102 F DEBUG : #03 pc 00000000002e38f4 /data/app/com.limbo.emu.main-xoGr7ZDZFnq8mXaagNshXQ==/lib/arm64/libqemu-system-x86_64.so
> 10-21 16:44:01.800 14102 14102 F DEBUG : #04 pc 00000000002d1db8 /data/app/com.limbo.emu.main-xoGr7ZDZFnq8mXaagNshXQ==/lib/arm64/libqemu-system-x86_64.so (bdrv_find_protocol+88)
> 10-21 16:44:01.800 14102 14102 F DEBUG : #05 pc 00000000002d6754 /data/app/com.limbo.emu.main-xoGr7ZDZFnq8mXaagNshXQ==/lib/arm64/libqemu-system-x86_64.so
> 10-21 16:44:01.800 14102 14102 F DEBUG : #06 pc 00000000002d7ae4 /data/app/com.limbo.emu.main-xoGr7ZDZFnq8mXaagNshXQ==/lib/arm64/libqemu-system-x86_64.so
> 10-21 16:44:01.800 14102 14102 F DEBUG : #07 pc 00000000002d6b60 /data/app/com.limbo.emu.main-xoGr7ZDZFnq8mXaagNshXQ==/lib/arm64/libqemu-system-x86_64.so
> 10-21 16:44:01.800 14102 14102 F DEBUG : #08 pc 00000000002dee20 /data/app/com.limbo.emu.main-xoGr7ZDZFnq8mXaagNshXQ==/lib/arm64/libqemu-system-x86_64.so (blk_new_open+104)
> 10-21 16:44:01.800 14102 14102 F DEBUG : #09 pc 00000000002ba114 /data/app/com.limbo.emu.main-xoGr7ZDZFnq8mXaagNshXQ==/lib/arm64/libqemu-system-x86_64.so
> 10-21 16:44:01.800 14102 14102 F DEBUG : #10 pc 0000000000327674 /data/app/com.limbo.emu.main-xoGr7ZDZFnq8mXaagNshXQ==/lib/arm64/libqemu-system-x86_64.so (drive_new+2308)
> 10-21 16:44:01.800 14102 14102 F DEBUG : #11 pc 00000000004d9cf0 /data/app/com.limbo.emu.main-xoGr7ZDZFnq8mXaagNshXQ==/lib/arm64/libqemu-system-x86_64.so
> 10-21 16:44:01.800 14102 14102 F DEBUG : #12 pc 0000000000625c40 /data/app/com.limbo.emu.main-xoGr7ZDZFnq8mXaagNshXQ==/lib/arm64/libqemu-system-x86_64.so (qemu_opts_foreach+116)
> 10-21 16:44:01.800 14102 14102 F DEBUG : #13 pc 00000000002bec14 /data/app/com.limbo.emu.main-xoGr7ZDZFnq8mXaagNshXQ==/lib/arm64/libqemu-system-x86_64.so (main+4112)
> 10-21 16:44:01.800 14102 14102 F DEBUG : #14 pc 00000000000013cc /data/app/com.limbo.emu.main-xoGr7ZDZFnq8mXaagNshXQ==/lib/arm64/liblimbo.so (Java_com_max2idea_android_limbo_jni_VMExecutor_start+744) (BuildId: 7822f9c542a97b60c4f018372e0cfcdba0b5e3e8)
> 10-21 16:44:01.800 14102 14102 F DEBUG : #15 pc 000000000002852c /data/app/com.limbo.emu.main-xoGr7ZDZFnq8mXaagNshXQ==/oat/arm64/base.odex (art_jni_trampoline+284)
> 10-21 16:44:01.800 14102 14102 F DEBUG : #16 pc 0000000000136334 /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 95b8a178dc0adad199ad5025808e3e5e)
> 10-21 16:44:01.800 14102 14102 F DEBUG : #17 pc 0000000000145060 /apex/com.android.runtime/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+244) (BuildId: 95b8a178dc0adad199ad5025808e3e5e)
> 10-21 16:44:01.800 14102 14102 F DEBUG : #18 pc 00000000002ddb64 /apex/com.android.runtime/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+384) (BuildId: 95b8a178dc0adad199ad5025808e3e5e)
> 10-21 16:44:01.800 14102 14102 F DEBUG : #19 pc 00000000002d9938 /apex/com.android.runtime/lib64/libart.so (bool art::interpreter::DoCall<true, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+656) (BuildId: 95b8a178dc0adad199ad5025808e3e5e)

on Android 10

**Pull request closed without merging**
