### PR TITLE
QEMU 5.0.0??? (Update???)

### PR DESCRIPTION
**Pull request by Pechayland**
Can you make Limbo PC Emulator v5.0.0 rebased with QEMU 5.0.x.
Add Architectures:
MIPS
RISC-V
HPPA
TriCore
Xtensa
UniCore 32
TileGX
SH-4
S390X
Nios2
OpenRISC
Moxie
MicroBlaze
M68K
LM32
CRIS
ALPHA

With All CPU Cores and Machines. 

Instead of The RAM Selection Change it to a Input And Selection of KB, MB, GB, and PB

Add all features of QEMU 5.0.0 in Limbo PC Emulator v4.2.0

Instead of separate apps make it into one.

Instead of selection of cpu cores make it an input.

Download the source code in the link and view the files: https://github.com/qemu/qemu

### CODE REVIEW

**Comment by THGStudios-alternative** [comment]
Make fix sound for SDL!

**Comment by THGStudios-alternative** [comment]
Limbo 4.2.0 Alpha changelog :
 - New architecture support
 - Fix sound for SDL interface

**Comment by krnltask** [comment]
> Limbo 4.2.0 Alpha changelog :
> 
> * New architecture support
> * Fix sound for SDL interface

Hi, can you upload the 4.2.0 Alpha? All other x86 versions are not working on my OnePlus 8 Pro, but ARM version is fine.

**Comment by THGStudios-alternative** [comment]
@krnltask Sorry, it still under construction by this versions. It's coming soon. I am not creator of the Limbo PC Emulator app. Sorry.

**Comment by krnltask** [comment]
> @krnltask Sorry, it still under construction by this versions. It's coming soon. I am not creator of the Limbo PC Emulator app. Sorry.

Ok thanks anyway. I'll wait for it.

**Comment by sudgdjshdzhsjdg** [comment]
please i am a simple tech enthusiastic and i want limbo emulator 4.2.0 or oth.  should be fast as the qemu pc or at least its older version limboemu 0.9.8 make the app more powerful to hand litte heavyweight OSes like mint linux etc. 

key points

should have more speed in emulating

compete with qemu

it should user friendly

**Comment by sudgdjshdzhsjdg** [comment]
make limbo fastest

**Comment by sudgdjshdzhsjdg** [comment]
**make limbo specially for x64 arm devices bacause there us no or severel x86 android devices in the market so users should have more options of x64 arm devices**

**Comment by nataniefgf** [comment]
> @krnltask Sorry, it still under construction by this versions. It's coming soon. I am not creator of the Limbo PC Emulator app. Sorry.

how can i download limbo 4.2.0 alpha

**Comment by nataniefgf** [comment]
make limbo fast and heavyweight like qemu 5.0.0 to run mint linux

**Comment by reynan2020** [comment]
Any updates? I'm having trouble compiling Limbo x86 Emulator with QEMU 3.1.0 and QEMU 4.0.0. Can someone provide a compiled (apk file) with QEMU 3.1.0?

**Comment by vmobilis** [comment]
Version 5.0.0 crashes on ARM7 Android 8.0 with "**seccomp prevented call to disallowed arm system call 349**" message (VM with default settings after clean install).
Any chance that it can be fixed or I better buy an Android 10 phone?
And thank you in any case!
```
F libc    : Fatal signal 31 (SIGSYS), code 1 in tid 8571 (VMExecutor)
...
F DEBUG   : signal 31 (SIGSYS), code 1 (SYS_SECCOMP), fault addr --------
F DEBUG   : Cause: seccomp prevented call to disallowed arm system call 349
F DEBUG   :     r0 ffffffff  r1 c1ef99c0  r2 00000008  r3 c1efa9c8
F DEBUG   :     r4 00000000  r5 c1ef99c0  r6 00000000  r7 0000015d
F DEBUG   :     r8 c1ef9a90  r9 c2007a00  sl da4b2650  fp c2bc3610
F DEBUG   :     ip c1ef9988  sp c1ef9978  lr c298a8b8  pc e5368eb0  cpsr 40010010
F DEBUG   : 
F DEBUG   : backtrace:
F DEBUG   :     #00 pc 00018eb0  /system/lib/libc.so (syscall+32)
F DEBUG   :     #01 pc 0067d8b4  /data/app/com.limbo.emu.main-6w48lvlc5o2AffQ3xSJHAw==/lib/arm/libqemu-system-x86_64.so (qemu_signalfd+44)
F DEBUG   :     #02 pc 0066f5a0  /data/app/com.limbo.emu.main-6w48lvlc5o2AffQ3xSJHAw==/lib/arm/libqemu-system-x86_64.so (qemu_init_main_loop+132)
F DEBUG   :     #03 pc 0058001c  /data/app/com.limbo.emu.main-6w48lvlc5o2AffQ3xSJHAw==/lib/arm/libqemu-system-x86_64.so (qemu_init+4316)
F DEBUG   :     #04 pc 00001c58  /data/app/com.limbo.emu.main-6w48lvlc5o2AffQ3xSJHAw==/lib/arm/liblimbo.so (Java_com_max2idea_android_limbo_jni_VMExecutor_start+1300)
F DEBUG   :     #05 pc 0005387f  /data/app/com.limbo.emu.main-6w48lvlc5o2AffQ3xSJHAw==/oat/arm/base.odex (offset 0x24000)
```

**Comment by i-am-human-hello** [comment]
Why do I get this On limbo-aarch64-androidARMv7-5.0.0

**Comment by Furanzeru** [comment]
I've my own Windows 7 iso. I used vmware to install because limbo keeps crashing, after i installed, i moved the vmdk file to limbo pc emulator (ver. 2.11.0), it really works perfectly and fast. I updated limbo pc emulator to 5.0.0 and i launched windows 7, everytime in startup, it keeps repeating to the start again. I need a help pls.

**Comment by Wiiplay123** [comment]
I'm on Android 8.1.0 and I'm getting Fatal signal 31 too,

`--------- beginning of crash`
`03-06 20:37:39.874 29510 30158 F libc    : Fatal signal 31 (SIGSYS), code 1 in tid 30158 (VMExecutor), pid 29510 (.limbo.emu.main)`

Couldn't find anything in the log file more specific than that, though.

**Comment by vmobilis** [comment]
@Wiiplay123, hi, there is a fixed version (of x86_64 emulator): https://github.com/limboemu/limbo/pull/127#issuecomment-761266748
By the way, to get more complete report, try to run Limbo two times. Sometimes it truncates the log and truncated part appears in next log.

**Pull request closed without merging**
