### PR TITLE
Please new CPU or better cpu

### PR DESCRIPTION
**Pull request by jamo-lcr**
Please new CPU or better cpu.I wrote this Here because the issue field ist Missing.

### CODE REVIEW

**Comment by L3P3** [comment]
Please close this pull request. Unless you magically have that better cpu at hand.

**Review by L3P3 — CHANGES_REQUESTED** [review]
There is a good reason for disabling issues tab, I am sure. Abusing pull requests is a bad way, now there is even less will to help you.

**Comment by gamemakerpspports** [comment]
please make sound not sound like crappy

**Comment by gamemakerpspports** [comment]
> please make sound not sound like crappy

BRUH WHO DESLIEK MY COMMENT

**Comment by L3P3** [comment]
@gamemakerpspports BRUH THIS THREAD IS CLOSED AND IT IS NOT THE TOPIC OF THIS THREAD

**Comment by gamemakerpspports** [comment]
> @gamemakerpspports BRUH THIS THREAD IS CLOSED AND IT IS NOT THE TOPIC OF THIS THREAD

ratio

**Comment by L3P3** [comment]
which ratio? look at my star projects!

**Pull request closed without merging**
