### PR TITLE
Added Korean Translation

### PR DESCRIPTION
**Pull request by obbcth**

### CODE REVIEW

**Comment by tolikes** [comment]
Add kernel support KVM for J7 2016 pleace!!

**Comment by obbcth** [comment]
The kernel must support kvm to use feature, but there is no way to support.
I'm not a developer, and ask this question for kernel developers.

**Comment by boerck** [comment]
This request is not about the KVM support. This is about Korean translation support. 
If you want to add KVM support in your kernel, you can build your kernel with this article.
[URL](https://limboemulator.weebly.com/android-arm-kvm---kernels.html)

**Comment by tolikes** [comment]
Thanks for info guys

**Comment by MVoloshin** [comment]
Why did you disable issues? How can I report bugs?

**Comment by MVoloshin** [comment]
How to contact him? No email, nothing at all

**Comment by boerck** [comment]
I dont't know. He didn't leave any email in limbo app or github

**Comment by ool10** [comment]
ㅎㅎ

**Pull request closed without merging**
