### PR TITLE
Limbo not compiling due to an error with nonexistent pkg-config

### PR DESCRIPTION
**Pull request by WaseemAlkurdi**
Dear @limboemu (@EnergyCube)

I am trying to compile Limbo for an aarch64 Android device and using the newest QEMU release from QEMU mainline.
Everything up until the `make limbo` step has gone smooth (well, nearly smooth), but `make limbo` goes all well until it stops with an error about a `pkg-config` that is missing from the toolchain. Android NDK doesn't provide a `pkg-config`, nor does Linaro's toolchain.
This is more properly an issue, but the issue tracker on this repo seems not to be enabled for some reason, so I've opted to file a pull request, because I'm really at a loss with this. I do apologize for this not being the proper method to communicate a bug :-(
This is the error:
```
No C++ compiler available; disabling C++ specific optional code

ERROR: pkg-config binary '/home/waseem/Downloads/android-ndk-r14b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android--pkg-config' not found
```
This is the complete output of `make limbo`:
https://termbin.com/9t9z

Thanks a lot!

### CODE REVIEW

**Comment by limboemu** [comment]
QEMU 2.9.1 is the only supported version at this time. I would suggest using Limbo 4.0.0 which has a series of fixes. To do so you will need to apply the patches found [here](https://github.com/limboemu/limbo/tree/master/limbo-android-lib/src/main/jni/patches). If you wish to compile for higher versions of QEMU you will need to update the qemu/configure script manually as well as any other files required. 

Check the [README.developers](https://github.com/limboemu/limbo/blob/master/README.developers) file to follow the instructions to download dependency libs, their required versions, and apply patches. Mind also the NDK requirements (specific version).

**Comment by limboemu** [comment]
More specifically all calls to pkg-config are suppressed by the applied patch. If you still see these errors it means that you are using a different QEMU version and you will to modify the qemu/configure file manually.

**Comment by WaseemAlkurdi** [comment]
@limboemu I have actually been following the instructions in README.developers to compile ... I also have the indicated version of the Android NDK.
I have tried to "make" my own patch, but the paragraph detailing this is a little short on details. From what I have understood though, I have done this command:
```
$ diff -ru --no-dereference ~/limbo/limbo/limbo-android-lib/src/main/jni/qemu/ ./ | grep -v '^Only in' > ../patches/qemu-3.1.50.patch
```
where `/tmp/qemu-3.1.50` is the new QEMU version and `./` is the old (2.9.0) one.
This is the patch that was generated:
https://filebin.ca/4aoRmEgOsuwy/qemu-3.1.50.patch
(Tried to copy it as to upload to Pastebin.com, but the file is too huge for the clipboard)

I am actually using a different QEMU version (3.1.50), because I need to use `ramfb`, a new feature introduced after `qemu-3.0.0` ...
I tried using a "dummy" pkg-config (a shell script that always returns zero), but an error message says that  `libfdt1` is not installed ... while it *is* actually installed.
Do I symlink the x86_64 `pkg-config` from the host to the path requested by the guest? Or do you recommend that I simply comment out each and every reference to `pkg-config` in `./configure`?

**Comment by limboemu** [comment]
Actually the patch that you generated is against an old QEMU version so you will still need to do your modifications inside qemu/configure (commenting out the pkg-config calls). In fact you not only need to modify the configure file but a bunch of other files inside qemu for compatibility with android.

I suggest opening the [qemu-2.9.1.patch](https://github.com/limboemu/limbo/blob/master/limbo-android-lib/src/main/jni/patches/qemu-2.9.1.patch) file and study all the modifications. This will act as a guide to modify manually the corresponding files in QEMU 3.1.50. You might also need to modify additional files depending on how much the QEMU code has changed.

Note:
Generating the patch with the diff command is not needed for now but later if you publish your code changes for others to compile.

**Comment by WaseemAlkurdi** [comment]
I've tried commenting out references to `pkg-config`, but I'm still getting an error about a `libfdt1`, which claims that the library is not installed, while it actually is ... :-(

**Comment by WaseemAlkurdi** [comment]
I've tried commenting out references to `pkg-config`, but I'm still getting an error about a `libfdt1`, which claims that the library is not installed, while it actually is ... :-(

**Comment by limboemu** [comment]
You might be missing header libfdt_env.h usually for Ubuntu it is located in the kernel headers.
In any case you don't have it you can install libfdt-dev:

> sudo apt-get install libfdt-dev

**Comment by WaseemAlkurdi** [comment]
I already did, as soon as I have seen this error. Didn't change a thing though.

**Comment by WaseemAlkurdi** [comment]
Commenting out `pkg-config` references results in this:
```
No C++ compiler available; disabling C++ specific optional code

ERROR: sizeof(size_t) doesn't match GLIB_SIZEOF_SIZE_T.
       You probably need to set PKG_CONFIG_LIBDIR
       to point to the right pkg-config files for your
       build target
```

**Comment by limboemu** [comment]
Can you post your modified configure file?

**Comment by limboemu** [comment]
I'm not sure why it's not working for you. These are the only changes I had to make to get the configure file working which are very similar to the changes that worked for QEMU 2.9.1. Please have a look at [qemu-2.9.1.patch](https://github.com/limboemu/limbo/blob/master/limbo-android-lib/src/main/jni/patches/qemu-2.9.1.patch) this will act as a guide to make modifications for QEMU 3.1.0 makefile and source files to handle any further incompatibility issues.

diff qemu/configure /tmp/qemu-3.1.0/configure
2188,2189c2188
<   #error_exit "pkg-config binary '$pkg_config_exe' not found"
<   echo Ingoring pkg-config probe
---
>   error_exit "pkg-config binary '$pkg_config_exe' not found"
2927,2928c2926
<       #feature_not_found "sdl" "Install SDL2-devel"
<       echo Limbo: Ignoring SDL2-devel probe
---
>       feature_not_found "sdl" "Install SDL2-devel"
3002,3003d2999
< sdl=yes
<
3465c3461
< #glib_modules=gthread-2.0
---
> glib_modules=gthread-2.0
3573c3569
<   #error_exit "pixman >= 0.21.8 not present." \
---
>   error_exit "pixman >= 0.21.8 not present." \
3575d3570
<   echo Limbo: Ignoring pixman probe
3856,3857c3851
<   #preadv=yes
<   preadv=no
---
>   preadv=yes
3858a3853
>
4177,4178c4172
<   #signalfd=yes
<   signalfd=no
---
>   signalfd=yes

Also make sure you have applied the patch for glib 2.56.1:
cd ./limbo-android-lib/src/main/jni/glib/
patch -p1 < ../patches/glib-2.56.1.patch

Make sure you export the host and guest variables before you run make, ie:
export BUILD_HOST=armeabi-v7a
export BUILD_GUEST=x86_64-softmmu
make limbo

Have a look at the [README.developers](https://github.com/limboemu/limbo/blob/master/README.developers) file for all the steps. Best of luck.

**Comment by WaseemAlkurdi** [comment]
Thanks a million for the detailed instructions! I have applied the changes you described, and I'm now running a 'make limbo' ... hoping for the best!
Sorry for being absent for the past few days :-(

**Comment by WaseemAlkurdi** [comment]
Ah damn ... didn't work ...
This is my modified ./qemu/configure, as you requested: https://pastebin.com/raw/BhSvNb6j
And this is the output now:
```
No C++ compiler available; disabling C++ specific optional code
Ignoring pkg-config probe
./configure: 385: ./configure: /home/user/Downloads/android-ndk-r14b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android--pkg-config: not found
./configure: 385: ./configure: /home/user/Downloads/android-ndk-r14b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android--pkg-config: not found
./configure: 385: ./configure: /home/user/Downloads/android-ndk-r14b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android--pkg-config: not found
./configure: 385: ./configure: /home/user/Downloads/android-ndk-r14b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android--pkg-config: not found
./configure: 385: ./configure: /home/user/Downloads/android-ndk-r14b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android--pkg-config: not found
Ignoring SDL probe
./configure: 2628: test: -lt: unexpected operator
./configure: 3189: ./configure: Syntax error: "else" unexpected
make[2]: *** [/home/user/limbo/limbo/limbo-android-lib/src/main/jni/android-config/android-qemu-config.mak:209: config] Error 2
make[2]: Leaving directory '/home/user/limbo/limbo/limbo-android-lib/src/main/jni'
make[1]: *** [Makefile:231: config-qemu] Error 2
make[1]: Leaving directory '/home/user/limbo/limbo/limbo-android-lib/src/main/jni'
make: *** [Makefile:273: limbo] Error 2
```
Thanks again for your assistance!

**Comment by limboemu** [comment]
Unfortunately I won't have the time to provide full support for going through all changes required for QEMU 3.1.0 right now. Usually it takes a **very long time** ironing out the details of patching new versions of QEMU. Such task might take weeks or even months. If you want to wait I might create a branch for 3.1.0 in the future though I don't know when it will happen. The good news is that you can always compile limbo with QEMU 2.9.1 which is fully supported and tested.

Anyway for now I can help you a little with these errors, note the line numbers:

./configure: **2628**: test: -lt: unexpected operator
I don't think your configure file is from QEMU 3.1.0 so I have a hard time helping you with this error. Though I can tell it's coming from the SDL lib probe so I would suggest study that portion of the configure file and see what changes you have already made that could be causing this.

./configure: **3189**: ./configure: Syntax error: "else" unexpected
For the second error it's more straightforward. These are your changes:
Line 3189:
elif test "$pixman" = "system"; then
   \# pixman version has been checked above
 \#  pixman_cflags=$($pkg_config --cflags pixman-1)
 \#  pixman_libs=$($pkg_config --libs pixman-1)
 else

It seems you commented out all the commands under the **elif** which is why it complains. You can insert an no-op command with a **:** right after your last commented line to suppress this error, see [here](https://stackoverflow.com/questions/17583578/what-command-means-do-nothing-in-a-conditional-in-bash). Though I'm not sure why you commented pixman to begin with. You can certainly omit the **--with-system-pixman** argument to the configure file to avoid all this. You can look at [android-qemu-config.mak](https://github.com/limboemu/limbo/blob/master/limbo-android-lib/src/main/jni/android-config/android-qemu-config.mak) for the use of this option and the other arguments that are passed to qemu/configure. Also have a look at the other **important Makefiles** outlined in [README.Developers](https://github.com/limboemu/limbo/blob/master/README.developers) under section **6. Development**.

**Comment by WaseemAlkurdi** [comment]
QEMU 2.9.1 is fine for most uses, but QEMU 3.x adds a new feature, `ramfb`, that is necessary for running Windows 10 ARM under KVM/QEMU. 
Regarding the `configure` files, I actually lost track of which version of QEMU each `configure` file comes from (not a good idea to call your files `configure`, `configure.OLD`, and `configure.FIXED`!) I'm going to `wget` the latest configure from the QEMU version I'm targeting and will try again.
And about the error at **3189**, this was purely unintended, as a result of rushed application of the `#` weapon to these lines.
I will try again, though I doubt it would compile, due to the huge number of changes needed, as you kindly explained.
Until you get the time to create a branch with a newer QEMU version, I think I'll make do with compiling regular QEMU in a Linux `chroot` on my Android phone, then VNC'ing the result to a VNC viewer, either on my phone or on my laptop.
Many, many heartfelt thanks!

**Pull request closed without merging**
